### ISSUE TITLE
buffer.clear() method not found when running on Java 8 

### ISSUE THREAD

**Issue by rexthk** [neowu/core-ng-project#8]
Here is my stack trace:

Using Java 1.8.0_152-release

2017-12-20T08:15:50.336Z [XNIO-1 task-2] DEBUG c.f.i.log.ActionLog - [context] method=POST
2017-12-20T08:15:50.336Z [XNIO-1 task-2] ERROR c.f.i.log.LogManager - [java.lang.NoSuchMethodError] java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	**at core.framework.impl.web.request.RequestBodyReader.read(RequestBodyReader.java:47)
	at core.framework.impl.web.HTTPServerIOHandler.handleRequest(HTTPServerIOHandler.java:38)**
	at io.undertow.server.protocol.http2.Http2UpgradeHandler.handleRequest(Http2UpgradeHandler.java:129)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:254)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

**Comment by AllisonLiang** [comment]
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 1509
Date: Wed, 20 Dec 2017 08:46:25 GMT

<html><body><h1>Error</h1><p>java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;</p><pre>java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
    at core.framework.impl.web.request.RequestBodyReader.read(RequestBodyReader.java:47)
    at core.framework.impl.web.HTTPServerIOHandler.handleRequest(HTTPServerIOHandler.java:38)
    at io.undertow.server.protocol.http2.Http2UpgradeHandler.handleRequest(Http2UpgradeHandler.java:129)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
    at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:254)
    at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
    at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:151)
    at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
    at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)
    at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
    at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
    at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
    at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
    at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
    at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
    at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
</pre></body></html>

Response code: 500 (Internal Server Error); Time: 99ms; Content length: 1509 bytes

**Comment by neowu** [comment]
it seems i can't publish with jdk 9, I will republish with jdk 8

**Comment by neowu** [comment]
I republished 5.2.8.1, and verified, please let me know if you see any other issue
